// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// prettier-ignore
const awsmobile = {
    'aws_project_region': 'ap-northeast-1',
    'aws_cognito_identity_pool_id': 'ap-northeast-1:61e08b01-eb11-432b-b8f1-3b14716a4a95',
    'aws_cognito_region': 'ap-northeast-1',
    'aws_user_pools_id': 'ap-northeast-1_9gNlBRJ5W',
    'aws_user_pools_web_client_id': '2l2l20d00svspf8ogc8offdhp3',
    'oauth': {
        'domain': 'wsp-prod-auth.auth.ap-northeast-1.amazoncognito.com',
        'scope': [
            'phone',
            'email',
            'openid',
            'profile',
            'aws.cognito.signin.user.admin',
        ],
        'redirectSignIn': 'http://localhost/',
        'redirectSignOut': 'http://localhost/',
        'responseType': 'code',
    },
    'federationTarget': 'COGNITO_USER_POOLS',
    'aws_cloud_logic_custom': [
        {
            'name': 'wsp-prod-api-v1',
            'endpoint': 'https://etlb3b2mw3.execute-api.ap-northeast-1.amazonaws.com/prod/v1',
            'region': 'ap-northeast-1',
        },
        {
            'name': 'wsp-prod-cdn-v1',
            'endpoint': 'https://cdn.whospick.com/v1',
            'region': 'ap-northeast-1',
        },
    ],
    'aws_appsync_graphqlEndpoint': 'https://qajtwwj6ebg5xcl3i4lyranzk4.appsync-api.ap-northeast-1.amazonaws.com/graphql',
    'aws_appsync_region': 'ap-northeast-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
    'aws_user_files_s3_bucket': 'wsp-prod-file',
    'aws_user_files_s3_bucket_region': 'ap-northeast-1',
    'aws_content_delivery_bucket': 'wsp-prod-cms',
    'aws_content_delivery_bucket_region': 'ap-northeast-1',
    'aws_content_delivery_url': 'wsp-prod-src',
};
// export default awsmobile;
module.exports = awsmobile;
