require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'whospick_reactnative_actor' do
  config = use_native_modules!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!('Flipper' => '0.76.0')
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
